# Generated by Django 2.2.2 on 2020-06-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_fim_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_fim_app',
            name='input_data',
            field=models.IntegerField(default=0),
        ),
    ]
