# Generated by Django 2.2.2 on 2020-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_fim_app', '0003_auto_20200611_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_fim_app',
            name='family',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='predict_fim_app',
            name='motivation',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='predict_fim_app',
            name='pre_hospitalization_status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
